# Home Assistant Configuration Example
# Add these sections to your Home Assistant configuration.yaml

# MQTT Configuration
mqtt:
  # Switches controlled by the terminal
  switch:
    - name: "Vault Door"
      unique_id: "vault_door_switch"
      command_topic: "vault/door/command"
      state_topic: "vault/door/status"
      payload_on: "OPEN"
      payload_off: "CLOSE"
      state_on: "OPEN"
      state_off: "CLOSED"
      icon: mdi:door
      
    - name: "Security System"
      unique_id: "security_system_switch"
      command_topic: "security/command"
      state_topic: "security/status"
      payload_on: "ARM"
      payload_off: "DISARM"
      state_on: "ARMED"
      state_off: "DISARMED"
      icon: mdi:shield-check
      
    - name: "Emergency Lights"
      unique_id: "emergency_lights_switch"
      command_topic: "lights/emergency/command"
      state_topic: "lights/emergency/status"
      payload_on: "ON"
      payload_off: "OFF"
      icon: mdi:alarm-light

  # Sensors to monitor terminal status
  sensor:
    - name: "RobCo Terminal Status"
      unique_id: "robco_terminal_status"
      state_topic: "robco_terminal/status"
      icon: mdi:monitor
      
    - name: "RobCo Terminal Current Menu"
      unique_id: "robco_terminal_menu"
      state_topic: "robco_terminal/current_menu"
      icon: mdi:menu
      
    - name: "Vault Temperature"
      unique_id: "vault_temperature"
      state_topic: "vault/sensors/temperature"
      unit_of_measurement: "°F"
      device_class: temperature
      
    - name: "Vault Radiation Level"
      unique_id: "vault_radiation"
      state_topic: "vault/sensors/radiation"
      unit_of_measurement: "rads"
      icon: mdi:radioactive

  # Binary sensors for status monitoring
  binary_sensor:
    - name: "Vault Door Status"
      unique_id: "vault_door_status"
      state_topic: "vault/door/status"
      payload_on: "OPEN"
      payload_off: "CLOSED"
      device_class: door
      
    - name: "Security System Armed"
      unique_id: "security_armed_status"
      state_topic: "security/status"
      payload_on: "ARMED"
      payload_off: "DISARMED"
      device_class: safety

# Automations to simulate vault behavior
automation:
  # Simulate door opening/closing
  - id: vault_door_simulation
    alias: "Vault Door Response Simulation"
    trigger:
      - platform: mqtt
        topic: "vault/door/command"
    action:
      - delay: "00:00:02"  # 2 second delay to simulate door operation
      - service: mqtt.publish
        data:
          topic: "vault/door/status"
          payload: "{{ trigger.payload }}"
          
  # Security system response
  - id: security_system_simulation
    alias: "Security System Response"
    trigger:
      - platform: mqtt
        topic: "security/command"
    action:
      - delay: "00:00:01"
      - service: mqtt.publish
        data:
          topic: "security/status"
          payload: >
            {% if trigger.payload == "ARM" %}
              ARMED
            {% else %}
              DISARMED
            {% endif %}
            
  # Publish sensor data periodically
  - id: vault_sensor_updates
    alias: "Vault Sensor Data Updates"
    trigger:
      - platform: time_pattern
        minutes: "/5"  # Every 5 minutes
    action:
      - service: mqtt.publish
        data:
          topic: "vault/sensors/temperature"
          payload: "{{ range(65, 75) | random }}"
      - service: mqtt.publish
        data:
          topic: "vault/sensors/radiation"
          payload: "{{ range(0, 5) | random }}"

# Optional: Dashboard card for monitoring the terminal
lovelace:
  dashboards:
    vault-control:
      mode: yaml
      title: Vault Control
      icon: mdi:home-variant
      show_in_sidebar: true
      filename: vault_dashboard.yaml

# Dashboard content (create as vault_dashboard.yaml in your HA config directory)
# ---
# title: Vault-Tec Control Panel
# views:
#   - title: Main Control
#     cards:
#       - type: entities
#         title: "RobCo Terminal"
#         entities:
#           - sensor.robco_terminal_status
#           - sensor.robco_terminal_current_menu
#           
#       - type: entities
#         title: "Vault Systems"
#         entities:
#           - switch.vault_door
#           - switch.security_system
#           - switch.emergency_lights
#           
#       - type: entities
#         title: "Sensors"
#         entities:
#           - sensor.vault_temperature
#           - sensor.vault_radiation_level
#           
#       - type: history-graph
#         title: "Vault Environment"
#         entities:
#           - sensor.vault_temperature
#           - sensor.vault_radiation_level
#         hours_to_show: 24

# Scripts for complex actions
script:
  vault_emergency_lockdown:
    alias: "Emergency Vault Lockdown"
    sequence:
      - service: mqtt.publish
        data:
          topic: "vault/door/command"
          payload: "CLOSE"
      - service: mqtt.publish
        data:
          topic: "security/command"
          payload: "ARM"
      - service: mqtt.publish
        data:
          topic: "lights/emergency/command"
          payload: "ON"
      - service: notify.persistent_notification
        data:
          title: "Vault Emergency Lockdown"
          message: "Emergency lockdown initiated from RobCo Terminal"
          
  vault_daily_startup:
    alias: "Vault Daily Startup Sequence"
    sequence:
      - service: mqtt.publish
        data:
          topic: "security/command"
          payload: "DISARM"
      - delay: "00:00:05"
      - service: mqtt.publish
        data:
          topic: "vault/door/command"
          payload: "OPEN"
      - service: mqtt.publish
        data:
          topic: "lights/emergency/command"
          payload: "OFF"
