esphome:
  name: robco-terminal
  friendly_name: RobCo Terminal
  platformio_options:
    board_build.flash_mode: dio
    board_build.psram_type: opi
    board_build.flash_size: 16MB
    build_flags:
      - -DCORE_DEBUG_LEVEL=1
      - -DCONFIG_ASYNC_TCP_STACK_SIZE=8192
      - -DCONFIG_ASYNC_TCP_PRIORITY=10

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  partitions: default_16MB.csv
  framework:
    type: esp-idf
    version: 5.3.0
    components:
      - name: espressif/esp_lvgl_port
        ref: 2.3.2
      - name: espressif/esp_lcd_touch_gt911
        ref: 1.1.0
      - name: lvgl/lvgl
        ref: 9.2.2
  variant: esp32s3

logger:
  level: INFO
  baud_rate: 115200
  hardware_uart: UART0
  logs:
    component: INFO
    robco_display: INFO
    ota: INFO
    wifi: INFO

psram:
  mode: octal
  speed: 80MHz

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  fast_connect: true
  output_power: 20dB
  reboot_timeout: 0s

mqtt:
  broker: !secret mqtt_broker
  port: 1883
  username: !secret mqtt_username
  password: !secret mqtt_password

captive_portal:

ota:
  platform: esphome
  password: !secret ota_password
  port: 3232

safe_mode:
  reboot_timeout: 10min
  num_attempts: 3

external_components:
  - source:
      type: local
      path: components

pico_io_extension:
  id: pico_io
  rx_pin: 17
  tx_pin: 18

robco_display:
  id: test
  pico_io_extension: pico_io
  open_vault_door_switch: open_vault_door_switch
  close_vault_door_switch: close_vault_door_switch
  red_light_pin: 21
  green_light_pin: 17

switch:
  - platform: template
    name: "Open Vault Door"
    id: open_vault_door_switch
    turn_on_action:
      - mqtt.publish:
          topic: garage/door/set
          payload: open
      - switch.turn_off: open_vault_door_switch
  - platform: template
    name: "Close Vault Door"
    id: close_vault_door_switch
    turn_on_action:
      - mqtt.publish:
          topic: garage/door/set
          payload: close
      - switch.turn_off: close_vault_door_switch

text_sensor:
  - platform: mqtt_subscribe
    name: "Vault Door State"
    id: vault_door_state
    topic: garage/state
    on_value:
      then:
        - lambda: |-
            id(test).set_vault_door_state(x);
