esphome:
  name: robco-terminal
  friendly_name: RobCo Hello World
  platformio_options:
    board_build.flash_mode: dio
    board_build.psram_type: opi
    board_build.flash_size: 16MB
    build_flags:
      - -DCORE_DEBUG_LEVEL=1
      - -DCONFIG_ASYNC_TCP_STACK_SIZE=8192
      - -DCONFIG_ASYNC_TCP_PRIORITY=10

esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  partitions: default_16MB.csv
  framework:
    type: esp-idf
  variant: esp32s3

logger:
  level: DEBUG
  baud_rate: 115200
  hardware_uart: UART0
  logs:
    component: DEBUG
    hello_world: DEBUG
    ota: INFO
    wifi: INFO

psram:
  mode: octal
  speed: 80MHz

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  power_save_mode: none
  fast_connect: true
  output_power: 20dB
  reboot_timeout: 0s
  ap:
    ssid: "RobCo Hello World Fallback"
    password: "robco123"

captive_portal:

ota:
  platform: esphome
  password: !secret ota_password
  port: 3232

safe_mode:
  disabled: true  # Disable for debugging; re-enable later
  reboot_timeout: 10min
  num_attempts: 3

external_components:
  - source:
      type: local
      path: components

# Initialize the hello_world component
hello_world:
  id: test
